# Generated by Django 5.0.1 on 2024-05-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("abertura_ordem", "0008_areamanutencao_tipomanutencao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_execucao", models.IntegerField()),
                ("data_hora_inicio", models.DateTimeField()),
                ("data_hora_fim", models.DateTimeField()),
                ("operadores", models.CharField(max_length=200)),
                (
                    "obs_manutencao",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("execucao", "Em execução"),
                            ("andamento", "Em andamento"),
                            ("finalizada", "Finalizada"),
                            ("aguardando", "Aguardando material"),
                        ],
                        max_length=20,
                    ),
                ),
                ("maquina_parada", models.BooleanField(default=False)),
                ("exec_maq_parada", models.BooleanField(default=False)),
                ("apos_exec_maq_parada", models.BooleanField(default=False)),
                (
                    "area_manutencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="execucao_area_manutencao",
                        to="abertura_ordem.areamanutencao",
                    ),
                ),
                (
                    "id_ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execucao_id_ordem",
                        to="abertura_ordem.ordens",
                    ),
                ),
                (
                    "tipo_manutencao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="execucao_tipo_manutencao",
                        to="abertura_ordem.tipomanutencao",
                    ),
                ),
            ],
            options={
                "unique_together": {("id_ordem", "n_execucao")},
            },
        ),
    ]
