# Generated by Django 5.0.1 on 2024-05-08 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abertura_ordem", "0008_areamanutencao_tipomanutencao"),
        ("gerenciador_ordens", "0002_alter_execucao_n_execucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execucao",
            name="operadores",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="execucao_operador",
                to="abertura_ordem.operador",
            ),
        ),
    ]
