# Generated by Django 5.0.1 on 2024-05-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abertura_ordem", "0008_areamanutencao_tipomanutencao"),
        ("gerenciador_ordens", "0003_alter_execucao_operadores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execucao",
            name="operadores",
        ),
        migrations.AddField(
            model_name="execucao",
            name="operadores",
            field=models.ManyToManyField(
                related_name="execucao_operador", to="abertura_ordem.operador"
            ),
        ),
    ]
