# Generated by Django 5.0.1 on 2024-05-09 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gerenciador_ordens", "0005_alter_execucao_id_ordem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="execucao",
            name="apos_exec_maq_parada",
        ),
    ]
