# Generated by Django 4.2.13 on 2024-05-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abertura_ordem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordens',
            name='id_ordem',
        ),
        migrations.AddField(
            model_name='ordens',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
