# Generated by Django 4.2.13 on 2024-05-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abertura_ordem', '0002_remove_ordens_id_ordem_ordens_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinasolda',
            name='setor',
            field=models.CharField(max_length=200),
        ),
    ]
