# Generated by Django 5.0.1 on 2024-05-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abertura_ordem", "0006_operador_ativo_solicitantes_ativo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquina",
            name="setor_maquina_solda",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maquina_setor_solda",
                to="abertura_ordem.maquinasolda",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordens",
            name="foto",
            field=models.ImageField(blank=True, default=1, upload_to="photo/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordens",
            name="local_maquina",
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordens",
            name="setor_maquina_solda",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens_maquina_solda",
                to="abertura_ordem.maquinasolda",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordens",
            name="video",
            field=models.ImageField(blank=True, default=1, upload_to="video/"),
            preserve_default=False,
        ),
    ]
