# Generated by Django 5.0.1 on 2024-05-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("abertura_ordem", "0009_alter_maquina_setor_maquina_solda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquina",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="maquina_setor",
                to="abertura_ordem.setor",
            ),
        ),
        migrations.AlterField(
            model_name="ordens",
            name="maquina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordens_maquina",
                to="abertura_ordem.maquina",
            ),
        ),
        migrations.AlterField(
            model_name="ordens",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordens_setor",
                to="abertura_ordem.setor",
            ),
        ),
        migrations.AlterField(
            model_name="ordens",
            name="setor_maquina_solda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordens_maquina_solda",
                to="abertura_ordem.maquinasolda",
            ),
        ),
        migrations.AlterField(
            model_name="ordens",
            name="solicitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordens_solicitantes",
                to="abertura_ordem.solicitantes",
            ),
        ),
        migrations.AlterField(
            model_name="solicitantes",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="solicitante_setor",
                to="abertura_ordem.setor",
            ),
        ),
    ]
